<a href="https://colab.research.google.com/github/banshita209/Data-Science-and-Machine-Learning-with-Python/blob/master/Assignment4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import the numpy package under the name np and Print the numpy version and the configuration 

In [2]:
pip install numpy

In [3]:
import numpy as np
np.__version__

'1.19.5'

# Create a null vector of size 10

In [4]:
l=np.zeros(10)
l

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# Create Simple 1-D array and check type and check data types in array

In [5]:
a=np.array([1,2,3,4])
print(a.dtype)

int64


# How to find number of dimensions, bytes per element and bytes of memory used?

In [14]:
b=np.arange(100)
print("-----arrray---")
print(b)
print("="*50)
print("Dimension of array :",b.ndim)
print("Memory used :",b.itemsize*b.size)

-----arrray---
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
Dimension of array : 1
Memory used : 800


# Create a null vector of size 10 but the fifth value which is 1

In [15]:
a=np.zeros(10)
a[4]=1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#Create a vector with values ranging from 10 to 49

In [17]:
a=np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

# Reverse a vector (first element becomes last)

In [21]:
sorted(a,reverse=True)

[49,
 48,
 47,
 46,
 45,
 44,
 43,
 42,
 41,
 40,
 39,
 38,
 37,
 36,
 35,
 34,
 33,
 32,
 31,
 30,
 29,
 28,
 27,
 26,
 25,
 24,
 23,
 22,
 21,
 20,
 19,
 18,
 17,
 16,
 15,
 14,
 13,
 12,
 11,
 10]

In [24]:
a[:-1]

[49,
 48,
 47,
 46,
 45,
 44,
 43,
 42,
 41,
 40,
 39,
 38,
 37,
 36,
 35,
 34,
 33,
 32,
 31,
 30,
 29,
 28,
 27,
 26,
 25,
 24,
 23,
 22,
 21,
 20,
 19,
 18,
 17,
 16,
 15,
 14,
 13,
 12,
 11]

# Create a 3x3 matrix with values ranging from 0 to 8

In [26]:
c=np.arange(0,9).reshape(3,3)
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Find indices of non-zero elements from [1,2,0,0,4,0]

In [28]:
a1=np.array([1,2,0,0,4,0])
np.nonzero(a1)

(array([0, 1, 4]),)

# Create a 3x3 identity matrix

In [30]:
a2=np.identity(3)
a2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Create a 3x3x3 array with random values

In [32]:
a3=np.random.random((3,3,3))
a3

array([[[0.00552659, 0.50538993, 0.39408704],
        [0.84105638, 0.23577798, 0.9843365 ],
        [0.33327162, 0.11752803, 0.35969791]],

       [[0.71801843, 0.22756141, 0.40255597],
        [0.23173876, 0.44463801, 0.68489852],
        [0.22527419, 0.9627717 , 0.22110211]],

       [[0.82412872, 0.75583674, 0.11691851],
        [0.56209094, 0.36096858, 0.87139512],
        [0.55036706, 0.66391367, 0.91404349]]])

# Create a 10x10 array with random values and find the minimum and maximum values

In [36]:
a4=np.random.random((10,10))
print(a4)
print("*"*80)
print("maximum in above array : ",a4.max())
print("minimum in above array : ",a4.min())

[[0.6035926  0.41992231 0.99719424 0.52344915 0.66766904 0.58486671
  0.71527791 0.9030273  0.08159561 0.10836313]
 [0.11528274 0.37051131 0.98431175 0.99794981 0.2544623  0.37739457
  0.16135078 0.20540737 0.03278308 0.06235572]
 [0.07107292 0.96299121 0.29959981 0.6901134  0.83907879 0.18961901
  0.94053195 0.52408621 0.9404287  0.14158619]
 [0.30607743 0.76663688 0.31564457 0.15116538 0.96902552 0.9326253
  0.82815534 0.3506106  0.98333982 0.05135291]
 [0.65556592 0.66459909 0.76834845 0.44348703 0.31144069 0.64365406
  0.08444902 0.85783287 0.89562231 0.7975739 ]
 [0.75907365 0.88480756 0.22452341 0.92447211 0.87136066 0.83895114
  0.60161501 0.17152175 0.20035968 0.13388091]
 [0.07666532 0.48179797 0.40443181 0.56865227 0.22046333 0.41690414
  0.61430388 0.2798868  0.78356501 0.30435216]
 [0.11475118 0.30253735 0.61148865 0.42444312 0.15611007 0.55761149
  0.81940202 0.47646774 0.91723846 0.77027124]
 [0.27926343 0.25894695 0.84640547 0.02074145 0.75657003 0.16678084
  0.86631896 

# Create a random vector of size 30 and find the mean value

In [39]:
a5=np.random.random(10)
print(a5)
print("#"*80)
print("mean of the value of above array is  :",a5.mean())

[0.45738747 0.91264406 0.70652389 0.91001468 0.59004326 0.30741916
 0.89164003 0.72323286 0.61963196 0.69631221]
################################################################################
mean of the value of above array is  : 0.6814849586018016


# Create a 2d array with 1 on the border and 0 inside

In [42]:
#creates a 2d array of 4*4 with all 1's
a6=np.ones((4,4))
#print(a6)

#for row : from 1st row upto last one 
#fro column : from 1st column upto last one 
a6[1:-1,1:-1]=0
print(a6)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


# How to add a border (filled with 0's) around an existing array? 

In [44]:
a6=np.pad(a6, pad_width=1, mode='constant', constant_values=0)
print(a6)

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 1. 0.]
 [0. 1. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


# How to Accessing/Changing specific elements, rows, columns, etc in Numpy array?

Example -
[[ 1 2 3 4 5 6 7] [ 8 9 10 11 12 13 14]]

Get 13, get first row only, get 3rd column only, get [2, 4, 6], replace 13 by 20

In [58]:
 a7=np.array([[ 1, 2, 3, 4, 5, 6, 7], [ 8, 9, 10, 11, 12, 13, 14]])
 print(a7)
 #a7[0,3]=20
 print("1st row : ",a7[0])
 print("3rd column : ",a7[:,3])

 ##
 ##
 ##

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
1st row :  [1 2 3 4 5 6 7]
3rd column :  [ 4 11]


# How to Convert a 1D array to a 2D array with 2 rows

In [59]:
a8=np.array([[ 1, 2, 3, 4, 5, 6, 7], [ 8, 9, 10, 11, 12, 13, 14]])
a8.flatten()


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

In [63]:
a = np.array([1,2,3])
print(np.r_[(np.repeat(a, 3), np.tile(a, 3))])
      

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


# Write a program to show how Numpy taking less memory compared to Python List?

In [65]:
import numpy as np

print("-"*10,"list","-"*10)
l=range(1000)

# this module is used to calculate size
import sys
a=10
print(sys.getsizeof(a)) #memory alocallted to a

#here, one int value takes 28 bytes in a list 
print(sys.getsizeof(a)*len(l))
print("-"*10,"numpy array","-"*10)
a1=np.arange(1000)
print(a1.size)

#to check each item in numpy array 
print(a1.size*a1.itemsize)

---------- list ----------
28
28000
---------- numpy array ----------
1000
8000


# Write a program to show how Numpy taking less time compared to Python List?

In [66]:
import time
import sys

print("-"*10,"list","-"*10)
size = 1000000
l1=range(size)
l2=range(size)

#starting timer
start=time.time()
#2 iterator are taken, inside zip we put both the list, one element from l1 will be put in x and one element from l2 will be put in y
result=[(x+y) for x,y in zip(l1,l2)]
#subtracting the when loop began with after excution of loop
print((time.time()-start)*1000)


print("-"*10,"numpy array","-"*10)
n1=np.arange(size)
n2=np.arange(size)

#starting timer
start=time.time()

result=n1+n2
#subtracting the when loop began with after excution of loop
#time is in micro sec that we mutlipled it to 1000
print((time.time()-start)*1000)

---------- list ----------
140.52438735961914
---------- numpy array ----------
15.46478271484375
