<a href="https://colab.research.google.com/github/banshita209/Data-Science-and-Machine-Learning-with-Python/blob/master/Assignment4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import the numpy package under the name np and Print the numpy version and the configuration 

In [ ]:
pip install numpy

In [2]:
import numpy as np
np.__version__

'1.19.5'

# Create a null vector of size 10

In [ ]:
l=np.zeros(10)
l

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# Create Simple 1-D array and check type and check data types in array

In [ ]:
a=np.array([1,2,3,4])
print(a.dtype)

int64


# How to find number of dimensions, bytes per element and bytes of memory used?

In [ ]:
b=np.arange(100)
print("-----arrray---")
print(b)
print("="*50)
print("Dimension of array :",b.ndim)
print("Memory used :",b.itemsize*b.size)

-----arrray---
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
Dimension of array : 1
Memory used : 800


# Create a null vector of size 10 but the fifth value which is 1

In [ ]:
a=np.zeros(10)
a[4]=1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#Create a vector with values ranging from 10 to 49

In [ ]:
a=np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

# Reverse a vector (first element becomes last)

In [ ]:
sorted(a,reverse=True)

[49,
 48,
 47,
 46,
 45,
 44,
 43,
 42,
 41,
 40,
 39,
 38,
 37,
 36,
 35,
 34,
 33,
 32,
 31,
 30,
 29,
 28,
 27,
 26,
 25,
 24,
 23,
 22,
 21,
 20,
 19,
 18,
 17,
 16,
 15,
 14,
 13,
 12,
 11,
 10]

In [ ]:
a[:-1]

[49,
 48,
 47,
 46,
 45,
 44,
 43,
 42,
 41,
 40,
 39,
 38,
 37,
 36,
 35,
 34,
 33,
 32,
 31,
 30,
 29,
 28,
 27,
 26,
 25,
 24,
 23,
 22,
 21,
 20,
 19,
 18,
 17,
 16,
 15,
 14,
 13,
 12,
 11]

# Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
c=np.arange(0,9).reshape(3,3)
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Find indices of non-zero elements from [1,2,0,0,4,0]

In [ ]:
a1=np.array([1,2,0,0,4,0])
np.nonzero(a1)

(array([0, 1, 4]),)

# Create a 3x3 identity matrix

In [ ]:
a2=np.identity(3)
a2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Create a 3x3x3 array with random values

In [3]:
a3=np.random.random((3,3,3))
a3

array([[[0.81177332, 0.36959608, 0.36781937],
        [0.8104156 , 0.61255145, 0.48840755],
        [0.609042  , 0.49879086, 0.31881892]],

       [[0.11490539, 0.91926045, 0.09550774],
        [0.94732429, 0.33586025, 0.96837812],
        [0.16310445, 0.97096353, 0.85748947]],

       [[0.27065883, 0.2713411 , 0.49306203],
        [0.88935627, 0.92443744, 0.37984721],
        [0.06086712, 0.85638902, 0.23670046]]])

# Create a 10x10 array with random values and find the minimum and maximum values

In [4]:
a4=np.random.random((10,10))
print(a4)
print("*"*80)
print("maximum in above array : ",a4.max())
print("minimum in above array : ",a4.min())

[[0.30708233 0.15183362 0.33464944 0.97739827 0.23143584 0.52219754
  0.52091781 0.53319301 0.04778048 0.7579727 ]
 [0.5071841  0.31003152 0.50960769 0.9978155  0.34631272 0.77120892
  0.61513017 0.66025451 0.64595068 0.14341335]
 [0.55955665 0.56202611 0.4074005  0.55086706 0.75280356 0.82643618
  0.00800223 0.9212785  0.30709429 0.72048679]
 [0.97063086 0.32812261 0.14800321 0.94755194 0.16389181 0.4100113
  0.75112618 0.55216306 0.66473366 0.81281712]
 [0.6342575  0.73333291 0.75127619 0.58038194 0.05709662 0.80931364
  0.91195108 0.53581176 0.70007037 0.76766228]
 [0.18824436 0.54078737 0.41950743 0.21139899 0.39226192 0.70769487
  0.9898398  0.31517734 0.29426576 0.21086005]
 [0.76361625 0.37100038 0.39154151 0.34753928 0.37286002 0.16122804
  0.93425006 0.7818365  0.10987792 0.08035967]
 [0.07998717 0.39818895 0.59460604 0.33644445 0.87132701 0.16792804
  0.05562772 0.31718798 0.67221957 0.51087982]
 [0.52771893 0.15334139 0.8010841  0.44705762 0.69613857 0.39064802
  0.2082211  

# Create a random vector of size 30 and find the mean value

In [5]:
a5=np.random.random(10)
print(a5)
print("#"*80)
print("mean of the value of above array is  :",a5.mean())

[0.68880466 0.19394296 0.72928377 0.53331147 0.46344041 0.82699988
 0.63717682 0.54022021 0.98765058 0.92747639]
################################################################################
mean of the value of above array is  : 0.6528307149462835


# Create a 2d array with 1 on the border and 0 inside

In [6]:

#creates a 2d array of 4*4 with all 1's
a6=np.ones((4,4))
#print(a6)

#for row : from 1st row upto last one 
#fro column : from 1st column upto last one 
a6[1:-1,1:-1]=0
print(a6)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


# How to add a border (filled with 0's) around an existing array? 

In [7]:
a6=np.pad(a6, pad_width=1, mode='constant', constant_values=0)
print(a6)

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 1. 0.]
 [0. 1. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


# How to Accessing/Changing specific elements, rows, columns, etc in Numpy array?

Example -
[[ 1 2 3 4 5 6 7] [ 8 9 10 11 12 13 14]]

Get 13, get first row only, get 3rd column only, get [2, 4, 6], replace 13 by 20

In [11]:
 a7=np.array([[ 1, 2, 3, 4, 5, 6, 7], [ 8, 9, 10, 11, 12, 13, 14]])
 print(a7)
print("*"*10,"After updating the value","*"*10)
 a7[0,-2] = 20
 print(a7)
 print("1st row : ",a7[0])
 print("3rd column : ",a7[:,3])
 print("array's 2,4,6th columns : ",a7[0,1::2])


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
********** After updating the value **********
[[ 1  2  3  4  5 20  7]
 [ 8  9 10 11 12 13 14]]
1st row :  [ 1  2  3  4  5 20  7]
3rd column :  [ 4 11]
array's 2,4,6th columns :  [ 2  4 20]


# How to Convert a 1D array to a 2D array with 2 rows

In [12]:
a8=np.array([[ 1, 2, 3, 4, 5, 6, 7], [ 8, 9, 10, 11, 12, 13, 14]])
a8.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

In [13]:
a = np.array([1,2,3])
print(np.r_[(np.repeat(a, 3), np.tile(a, 3))])

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


# Write a program to show how Numpy taking less memory compared to Python List?

In [14]:
import numpy as np

print("-"*10,"list","-"*10)
l=range(1000)

# this module is used to calculate size
import sys
a=10
print(sys.getsizeof(a)) #memory alocallted to a

#here, one int value takes 28 bytes in a list 
print(sys.getsizeof(a)*len(l))
print("-"*10,"numpy array","-"*10)
a1=np.arange(1000)
print(a1.size)

#to check each item in numpy array 
print(a1.size*a1.itemsize)

---------- list ----------
28
28000
---------- numpy array ----------
1000
8000


# Write a program to show how Numpy taking less time compared to Python List?

In [15]:
import time
import sys

print("-"*10,"list","-"*10)
size = 1000000
l1=range(size)
l2=range(size)

#starting timer
start=time.time()
#2 iterator are taken, inside zip we put both the list, one element from l1 will be put in x and one element from l2 will be put in y
result=[(x+y) for x,y in zip(l1,l2)]
#subtracting the when loop began with after excution of loop
print((time.time()-start)*1000)


print("-"*10,"numpy array","-"*10)
n1=np.arange(size)
n2=np.arange(size)

#starting timer
start=time.time()

result=n1+n2
#subtracting the when loop began with after excution of loop
#time is in micro sec that we mutlipled it to 1000
print((time.time()-start)*1000)

---------- list ----------
142.55189895629883
---------- numpy array ----------
17.191410064697266
