<a href="https://colab.research.google.com/github/banshita209/banshita209-Data-Science-and-Machine-Learning-with-Python/blob/master/class5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy


*   if we define it in one line we can say : numerical python
*   its a library in python
* use for scientific computing  
* it contain n-dimension array object
* linear algebra caculation can be done in numpy
* multi dimenial operations are easy to perform
* it have good documentation so we can refer it whenever we have some doubt.
* 



# INstall numpy


*   in cmd :pip install numpy
*   anoconda install numpy for anoconda
* already onstalled in cloab



In [ ]:
pip install numpy

In [ ]:
import numpy as np
# rename numpy library to np for easier access
 

# Create 1-D array


In [ ]:
a=np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


nd array means: n dimension array


---

# 2-D Array

In [ ]:
a = np.array([[1,2,3],[10,20,30]])
print(a)
print(type(a))

[[ 1  2  3]
 [10 20 30]]
<class 'numpy.ndarray'>


In [ ]:
#this will create 2-D array of zeros
#zeros creates an array of zero
np.zeros((2,3)) 

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#this will create an array of an array a specific range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#create array with item between range of 2 to 10  
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#it will create array from range 2 to 3 with 0.1 interval between the items
np.arange(2,3,0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [ ]:
#it will create an array strarting from 1 to 4 with 6 items and these 6 items will be equally spaced ( diiference between every 2 element will be the same)
np.linspace(1,4,6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [ ]:
#it will create 
#Return an array representing the indices of a grid
np.indices((3,3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [ ]:
np.indices((2,2))

array([[[0, 0],
        [1, 1]],

       [[0, 1],
        [0, 1]]])

In [ ]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
#this fucntion return the datatype of the elements
print(a.dtype)

int64


# List v/s Numpy array


*   numpy array uses less memory then list
* numpy is more convenient
* faster than list



# less memory use example

In [ ]:
import numpy as np

l=range(1000)

# this module is used to calculate size
import sys
a=10
print(sys.getsizeof(a)) #memory alocallted to a

#here, one int value takes 28 bytes in a list 
print(sys.getsizeof(a)*len(l))

a1=np.arange(1000)
print(a1.size)

#to check each item in numpy array 
print(a1.size*a1.itemsize)

28
28000
1000
8000


# how numpy is faster

In [ ]:
#

import time
import sys

size = 1000000
l1=range(size)
l2=range(size)

#starting timer
start=time.time()
#2 iterator are taken, inside zip we put both the list, one element from l1 will be put in x and one element from l2 will be put in y
result=[(x+y) for x,y in zip(l1,l2)]
#subtracting the when loop began with after excution of loop
print((time.time()-start)*1000)

n1=np.arange(size)
n2=np.arange(size)

#starting timer
start=time.time()

result=n1+n2
#subtracting the when loop began with after excution of loop
#time is in micro sec that we mutlipled it to 1000
print((time.time()-start)*1000)


116.2574291229248
14.87278938293457


# numpy operations

In [ ]:
a=np.array([[1,2,3],[10,20,30]])
print(a.ndim)

2


In [ ]:
#size of one item
print(a.itemsize)

8


In [ ]:
#return data type of item
print(a.dtype)

int64


In [ ]:
#return no row and column
print(a.shape)

(2, 3)


In [ ]:
# return total no element
print(a.size)

6


# reshape

In [ ]:
#reshape() is used change the number of rows and column
a.reshape(3,2)
#move from left to right

array([[ 1,  2],
       [ 3, 10],
       [20, 30]])

#slicing a numpy array

In [ ]:
a

array([[ 1,  2,  3],
       [10, 20, 30]])

In [ ]:
a[0,0]

1

In [ ]:
a[0,1]

2

In [ ]:
#return all the element from all the row and 1st column
#a[0:,1] means consider all row( starting from 0) and return value of 1st column
a[0:,1]

array([ 2, 20])

In [ ]:
#select row from 0 to 2 and column after 3
a[0:2,1:]

array([[ 2,  3],
       [20, 30]])

In [ ]:
a=np.array([[1,2,3,4,5],[10,20,30,40,50]])
print(a.shape)

(2, 5)


In [ ]:
print(a.min())

1


In [ ]:
print(a.max())

50


In [ ]:
print(a.sum())

165


In [ ]:

print(a)
print("---sum fun---")
#axis=0 means sum will becolumn wise
print(np.sum(a,axis=0))
#axis=1 means sum will be row wise
print(np.sum(a,axis=1))

[[ 1  2  3  4  5]
 [10 20 30 40 50]]
---sum fun---
[11 22 33 44 55]
[ 15 150]


In [ ]:
#array mathematical operation
import numpy as np

x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])

print(x)
print(y)

print("----addition--------")
#element wise sum
print(x+y)
print(np.add(x,y))

print("-----subtraction------")
#subtraction
print(x-y)
print(np.subtract(x,y))

#

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
----addition--------
[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
-----subtraction------
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [ ]:
print(a)

[[ 1  2  3  4  5]
 [10 20 30 40 50]]


In [ ]:
#convert 2d array to 1 d array
print(a.flatten())

[ 1  2  3  4  5 10 20 30 40 50]


#pandas

*   used for data manipulation
*   data analysis
* generally used with tabular data 
* unlabelled data




Install panda


*   using cmd : pip install pandas
*   List item



In [ ]:
pip install pandas

series:


*  
*   List item




---
frames


In [ ]:
import pandas as pd
import numpy as np

a= np.array(['b','a','n','s','h','i'])
#converting numpy array to pandas series
p=pd.Series(a)
print(p)

0    b
1    a
2    n
3    s
4    h
5    i
dtype: object


In [ ]:
#random is written twice ​because it's random function from random category of numpy
s1=pd.Series(np.random.random(5),index=['a','b','c','d','e'])
print(s1)

a    0.983164
b    0.752692
c    0.039885
d    0.353619
e    0.023463
dtype: float64


In [ ]:
data={'pi':3.14,'e':2.71}
print(data)
s=pd.Series(data)
print(s)


{'pi': 3.14, 'e': 2.71}
pi    3.14
e     2.71
dtype: float64


In [ ]:
#accessing element using index
s1[1]

0.752692077055733