<a href="https://colab.research.google.com/github/banshita209/banshita209-Data-Science-and-Machine-Learning-with-Python/blob/master/class5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy


*   if we define it in one line we can say : numerical python
*   its a library in python
* use for scientific computing  
* it contain n-dimension array object
* linear algebra caculation can be done in numpy
* multi dimenial operations are easy to perform
* it have good documentation so we can refer it whenever we have some doubt.
* 



# INstall numpy


*   in cmd :pip install numpy
*   anoconda install numpy for anoconda
* already onstalled in cloab



In [1]:
pip install numpy

In [3]:
import numpy as np
# rename numpy library to np for easier access
 

# Create 1-D array


In [4]:
a=np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


nd array means: n dimension array


---

# 2-D Array

In [7]:
a = np.array([[1,2,3],[10,20,30]])
print(a)
print(type(a))

[[ 1  2  3]
 [10 20 30]]
<class 'numpy.ndarray'>
